---
- name: Set Hostname
  vars:
    interface: "{{ item.key }}"
  when: item.key is defined
  
- name: Set Status
  vars:
    status: "{{ item.value.state }}"
  when: item.value.state is defined
  
- name: Print Results
  debug:
    msg: "{{ interface }}, {{ status }}"
