---
- name: Set Defaults
  set_fact:
    interface: ''
    desc: ''
    stat: ''
    mac: ''
    ip: ''
    
- name: Set Interface
  set_fact:
    interface: "{{ item.key }}"
  when: item.key is defined
  
- name: Set Description
  set_fact:
    desc: "{{ item.value.description }}"
  when: item.value.description is defined
  
- name: Set Status
  set_fact:
    stat: "{{ item.value.state }}"
  when: item.value.state is defined
  
- name: Set Status 2
  set_fact:
    stat: "{{ item.value.operstatus }}"
  when: item.value.operstatus is defined
  
- name: Get MAC from table
  cli_command:
    command: "show mac address interf {{ item.key }}"
  register: mac_list
  when: item.key is search("Gig.*|gig.*|Fast.*|fast.*|Eth.*|eth.*")
  
- name: Set MAC address
  set_fact:
    mac: "{{ mac_list.stdout | regex_search('\\b(?:[0-9a-f]{4}\\.){2}[0-9a-f]{4}\\b') }}"
  when: mac_list.stdout is defined
  
- name: Get IP from ARP
  cli_command:
    command: "show ip arp | inc {{ mac }}"
  register: arp_list
  when: mac != ''
  
- name: Set IP address
  set_fact:
    ip: "{{ arp_list.stdout | regex_search('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b')"
  when: arp_list.stdout is defined
  
- name: Set IP address - fallback
  set_fact:
    ip: "{{ item.value.ipv4.address }}/{{ item.value.ipv4.masklen | default(' ') }}"
  when: item.value.ipv4.address is defined
  
- name: Write Line to CSV
  delegate_to: localhost
  shell: "echo '{{ interface }},{{ desc }},{{ stat }},{{ mac }},{{ ip }}' >> {{ csv_file }}"
