---
- name: Download OUI File From IEEE
  delegate_to: localhost
  get_url:
    url: "{{ oui_url }}"
    dest: /root
    mode: '0755'
    
- name: Create Vendor File
  delegate_to: localhost
  shell: "cat /root/oui.txt | grep '(base 16)' | cut -f3 > /root/vendor.txt"
  
- name: Create MAC File
  delegate_to: localhost
  shell: "cat /root/oui.txt | grep '(base 16)' | cut -f1 -d' ' > /root/mac.txt"
  
- name: Join MAC and Vendor files
  delegate_to: localhost
  shell: "paste /root/mac.txt /root/vendor.txt > /root/lookup.txt"
  
- name: Cleanup Temporary Files
  delegate_to: localhost
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /root/vendor.txt
    - /root/mac.txt
    
- name: Create CSV file and Write Header
  delegate_to: localhost
  lineinfile:
    path: "{{ csv_file }}"
    line: Port,Description,Status,Extended Status,Speed/Duplex,MAC Address,Vendor,IP Address,PoE
    create: yes

- name: Loop through interfaces
  include_tasks: loop.yml
  #debug:
    #msg: "{{ item }}"
  loop: "{{ lookup('dict', ansible_net_interfaces) }}"
  
- name: Email CSV
  delegate_to: localhost
  mail:
    host: 212.0.16.135
    port: 25
    subject: "Port Report For {{ ansible_net_hostname }}"
    body: Your report has been generated and is attached to this email.
    from: BBMUS@bbraunusa.com
    to: "{{ email }}"
    attach:
    - "{{ csv_file }}"

- name: Cleanup Local Files
  delegate_to: localhost
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ csv_file }}"
    - /root/oui.txt
    - /root/lookup.txt
