---
- name: Write CSV File and Header
  delegate_to: localhost
  shell: "echo 'Port,Description,Status,Mode,MAC Address,IP Address' > {{ csv_file }}"

- name: Loop through interfaces
  #include_tasks: loop.yml
  cli_command:
    command: "show running-config interface {{ item.key }}"
  register: int_conf
  debug:
    msg: {{ int_conf }}
  loop: "{{ lookup('dict', ansible_net_interfaces) }}"
