---
- name: Check for Lookup File
  delegate_to: localhost
  stat:
    path: /root/lookup.txt
  register: lookup_file
  
- name: Download OUI File From IEEE
  delegate_to: localhost
  get_url:
    url: "{{ oui_url }}"
    dest: /root
    mode: '0755'
    
- name: Create Vendor File
  delegate_to: localhost
  shell: "cat /root/oui.txt | grep '(base 16)' | cut -f3 > /root/vendor.txt"
  when: not lookup_file.stat.exists
  
- name: Create MAC File
  delegate_to: localhost
  shell: "cat /root/oui.txt | grep '(base 16)' | cut -f1 -d' ' > /root/mac.txt"
  when: not lookup_file.stat.exists
  
- name: Join MAC and Vendor files
  delegate_to: localhost
  shell: "paste /root/mac.txt /root/vendor.txt > /root/lookup.txt"
  when: not lookup_file.stat.exists
  
- name: Cleanup Temporary Files
  delegate_to: localhost
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /root/vendor.txt
    - /root/mac.txt
    
- name: Create CSV file and Write Header
  delegate_to: localhost
  lineinfile:
    path: "{{ csv_file }}"
    line: Port,Description,Status,Extended Status,Speed/Duplex,Port Type,VLAN,MAC Address,Vendor,IP Address,PoE
    create: yes
    
- name: Store OUI file as variable
  set_fact:
    oui_file: "{{ lookup('file', '/root/oui.txt') }}"
    
- name: Loop through interfaces
  include_tasks: loop.yml
  loop: "{{ lookup('dict', ansible_net_interfaces) }}"
  
- name: Email CSV
  delegate_to: localhost
  mail:
    host: 212.0.16.135
    port: 25
    subject: "Port Report For {{ ansible_net_hostname }}"
    body: Your report has been generated and is attached to this email.
    from: BBMUS@bbraunusa.com
    to: "{{ email }}"
    attach:
    - "{{ csv_file }}"

- name: Cleanup Local Files
  delegate_to: localhost
  file:
    path: "{{ csv_file }}"
    state: absent
