---
- name: Write CSV File and Header
  delegate_to: localhost
  shell: "echo 'Hostname,Port,Status,Description,VLAN ID,MAC Address,IP Address' > {{ csv_file }}"

#- name: Get Interfaces
#  debug:
#    msg: "{{ ansible_net_interfaces }}"
    
- name: Loop through interfaces
  debug:
    msg: "{{ item }}"
  loop: "{{ lookup('dict', ansible_net_interfaces) }}"
