---
- name: Write CSV File and Header
  delegate_to: localhost
  shell: "echo 'Port,Description,Status,Mode,MAC Address,IP Address' > {{ csv_file }}"

- name: Loop through interfaces
  include_tasks: loop.yml
  loop: "{{ lookup('dict', ansible_net_interfaces) }}"
  
- name: Email CSV
  delegate_to: localhost
  mail:
    host: 212.0.16.135
    port: 25
    subject: "Port Report For {{ hostname }}"
    body: Your report has been generated and is attached to this email.
    from: BBMUS@bbraunusa.com
    to: "{{ email }}"
    attach:
    - "/root/{{ csv_file }}"

- name: Delete Local CSV File
  delegate_to: localhost
  shell: "rm -f {{ csv_file }}"
