---
- name: Error Handling
  debug:
    msg: "no acceptable network OS found on target device"
  when: ansible_network_os not in [ 'ios', 'nxos' ]

- name: Gather IOS Facts
  ios_facts:
  when: ansible_network_os == "ios"
  
- name: Gather NS-OX Facts
  nxos_facts:
  when: ansible_network_os == "nxos"