---
- name: Set Defaults
  set_fact:
    desc: ''
    status: ''
    mac: ''

- name: Set Description
  set_fact:
    desc: "{{ ansible_net_interfaces[item.key] }}"
  when: ansible_net_interfaces[item.key] is defined