---
- name: Set Defaults
  set_fact:
    desc: ''
    status: ''
    mac: ''

- name: Set Description
  set_fact:
    desc: "{{ lookup('dict', 'ansible_net_interfaces[' + item.key + '][description]') }}"
  when: lookup('dict', 'ansible_net_interfaces[' + item.key + '][description]') is defined