---
- name: Create CSV file and Write Header
  delegate_to: localhost
  run_once: true
  lineinfile:
    path: "{{ csv_file }}"
    line: Hostname,IP Address,Model,Software Version,Platform,Serial Number
    create: yes

- name: Set Defaults
  set_fact:
    hostname: ''
    ip: ''
    model: ''
    version: ''
    platform: ''
    serial: ''
    
- name: Set Hostname
  set_fact:
    hostname: "{{ ansible_net_hostname }}"
  when: ansible_net_hostname is defined
  
- name: Set IP Address
  set_fact:
    ip: "{{ ansible_net_all_ipv4_addresses[0] }}"
    when: ansible_net_all_ipv4_addresses[0] is defined
    
- name: Set Model
  set_fact:
    model: "{{ ansible_net_model }}"
  when: ansible_net_model is defined
  
- name: Set Version
  set_fact:
    version: "{{ ansible_net_version }}"
  when: ansible_net_version is defined
  
- name: Set Platform
  set_fact:
    platform: "{{ ansible_net_platform }}"
  when: ansible_net_platform is defined
  
- name: Set Serial
  set_fact:
    serial: "{{ ansible_net_serialnum }}"
  when: ansible_net_serialnum is defined
  
- name: Write Line to CSV
  delegate_to: localhost
  lineinfile:
    path: "{{ csv_file }}"
    line: "{{ hostname }},{{ ip }},{{ model }},{{ version }},{{ platform }},{{ serial }}"

- name: Email CSV
  delegate_to: localhost
  run_once: true
  mail:
    host: 212.0.16.135
    port: 25
    subject: "Inventory Report"
    body: Your report has been generated and is attached to this email.
    from: BBMUS@bbraunusa.com
    to: "{{ email }}"
    attach:
    - "{{ csv_file }}"

- name: Delete Local CSV File
  delegate_to: localhost
  run_once: true
  file:
    path: "{{ csv_file }}"
    state: absent
