---
- name: Create CSV File and Write Header
  delegate_to: localhost
  run_once: true
  lineinfile:
    path: "{{ csv_file }}"
    line: Subnet, Alive Host Count
    create: yes

- name: Loop Through Subnets
  delegate_to: localhost
  shell: "python3 subnet_scan.py {{ item }}"
  loop: "{{ subnets }}"