---
- name: Perform Backup
  cli_command:
    commands:
    - command: "{{ tftp_config_backup }}"
      prompt: "[confirm]"
      answer: "\r"
    - command: "{{ tftp_vlan_backup }}"
      prompt: "[confirm]"
      answer: "\r"