---
- name: Perform Backup
  ios_command:
    commands:
    - command: "copy startup-config tftp://{{ tftp_server }}/{{ ios_hostname }}_config_{{ date }}"
      prompt: 
      - "Address or name of remote host [{{ tftp_server }}]?"
      - "Destination filename [{{ ios_hostname }}_config_{{ date }}]?"
      answer: 
      - "\r"
      - "\r"
    - command: "copy flash:vlan.dat tftp://{{ tftp_server }}/{{ ios_hostname }}_vlan.dat_{{ date }}"
      prompt:
      - "Address or name of remote host [{{ tftp_server }}]?"
      - "Destination filename [{{ ios_hostname }}_vlan.dat_{{ date }}]?"
      answer:
      - "\r"
      - "\r"