---
- name: Perform Backup
  ntc_save_config:
    platform: cisco_ios_ssh
    host: "{{ inventory_hostname }}"
    username: dunhbrus
    password: "{{ dunhbrus_pw }}"
    local_file: "/home/bbraun/test_{{ date }}"
    