---
- name: Find Old Files
  find:
    paths: "{{ cleanup_path }}"
    age: "{{ max_age }}"
    file_type: file
  register: old_files

- name: Remove Old Files
  file:
    path: "{{ item }}" 
    state: absent
  with_items: "{{ old_files | list }}"
